# Generated by Django 4.0.2 on 2022-03-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NWS', 'Новость'), ('ART', 'Статья')], default='NWS', max_length=3),
        ),
    ]
